---
deployer:
  database:
    user: root
    password: root
  user:
    path: "/var/www/vhosts"
    group: "www-data"
  web_server:
    type: "nginx"
    user: "www-data"
    port: 80
    available_path: "/etc/nginx/sites-available"
    enabled_path: "/etc/nginx/sites-enabled"
    domain_suffix: ".com"
  php_fpm:
    version: "7.1"
    pool_path: "/etc/php/7.1/fpm/pool.d"
    socket_path: "/var/run"