<?php


namespace rezozero\Deployer;

use rezozero\Deployer\Commands\CreateDatabaseUserCommand;
use rezozero\Deployer\Commands\CreateUnixUserCommand;
use rezozero\Deployer\Commands\DropDatabaseUserCommand;

class Application extends \Symfony\Component\Console\Application
{
    /**
     * @inheritDoc
     */
    public function getName()
    {
        return 'Rezo Zero Deployer'; // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getVersion()
    {
        return '2.0.0-alpha'; // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getDefaultCommands()
    {
        return array_merge(parent::getDefaultCommands(), [
            new CreateUnixUserCommand(),
            new CreateDatabaseUserCommand(),
            new DropDatabaseUserCommand(),
        ]);
    }
}